"""empty message

Revision ID: 6c7565e5c07a
Revises: 
Create Date: 2022-02-08 22:34:00.706546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7565e5c07a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_pokemon', sa.Column('poke_id', sa.Integer(), nullable=False))
    op.alter_column('user_pokemon', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('user_pokemon_pokemon_id_fkey', 'user_pokemon', type_='foreignkey')
    op.create_foreign_key(None, 'user_pokemon', 'pokemon', ['poke_id'], ['id'])
    op.drop_column('user_pokemon', 'pokemon_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_pokemon', sa.Column('pokemon_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_pokemon', type_='foreignkey')
    op.create_foreign_key('user_pokemon_pokemon_id_fkey', 'user_pokemon', 'pokemon', ['pokemon_id'], ['id'])
    op.alter_column('user_pokemon', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('user_pokemon', 'poke_id')
    # ### end Alembic commands ###
